### ISSUE TITLE
After run rails generate gcm_migrations command ----->next_migration_number': NotImplementedError (NotImplementedError)

### ISSUE THREAD

**Issue by ravindra9278** [dondeng/gcm_on_rails#33]
I am using rails 4.2.1
Ruby 2.2.1p85

/home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/generators/migration.rb:29:in `next_migration_number': NotImplementedError (NotImplementedError)
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/generators/migration.rb:41:in `set_migration_assigns!'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/generators/migration.rb:57:in `migration_template'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/gcm_on_rails-0.1.3/lib/generators/gcm_migrations_generator.rb:26:in `block in create_migrations'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/gcm_on_rails-0.1.3/lib/generators/gcm_migrations_generator.rb:24:in `each_pair'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/gcm_on_rails-0.1.3/lib/generators/gcm_migrations_generator.rb:24:in `create_migrations'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /var/www/html/preitmessage/releases/20151103031417/bin/rails:8:in `<top (required)>'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/daffolap-198/.rvm/gems/ruby-2.2.1@preitmessage/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/daffolap-198/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/daffolap-198/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

**Comment by dondeng** [comment]
Go I have never tested this on Rails 4, I have begun work to test it on
Talks 4 and Ruby 2.1.5. I could give more feed back then
